name: Benchmark APIs

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Benchmark mode (baseline|normal|stress|extreme)'
        required: false
        default: 'baseline'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [springboot, quarkus, gin]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build

      - name: Run containers
        run: docker compose up -d

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wrk python3 python3-pip
          pip3 install -r requirements.txt

      - name: Run benchmark script
        run: |
          echo "Running benchmark for mode: ${{ github.event.inputs.mode }}"
          sudo bash ./wrk_test.sh ${{ github.event.inputs.mode }}

      - name: Generate benchmark report
        run: python3 ./wrk_analysis.py

      - name: Upload benchmark report and charts
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-report
          path: |
            ./benchmark_report
            ./benchmark_charts
