name: Benchmark APIs

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Benchmark mode'
        required: true
        default: 'baseline'
        type: choice
        options:
          - short
          - baseline
          - normal
          - stress
          - extreme

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [springboot, quarkus, gin]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose wrk python3 python3-pip
          pip3 install -r requirements.txt

      - name: Run benchmark via Makefile
        run: |
          make MODE=${{ github.event.inputs.mode }}

      - name: Zip benchmark results
        run: |
          zip -r benchmark-${{ matrix.service }}-${{ github.event.inputs.mode }}.zip \
            benchmark_log benchmark_charts benchmark_report

      - name: Upload benchmark zip
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-${{ matrix.service }}-${{ github.event.inputs.mode }}
          path: benchmark-${{ matrix.service }}-${{ github.event.inputs.mode }}.zip
          retention-days: 7

